---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thevifco/repositories/the-vif-luxury-rivie
    - cd $DEPLOYPATH
    - /home/thevifco/nodevenv/backend/20/bin/npm install 2>&1 || /usr/bin/npm install 2>&1
    - /home/thevifco/nodevenv/backend/20/bin/npm run build 2>&1 || /usr/bin/npm run build 2>&1
    - /bin/cp -R $DEPLOYPATH/dist/* /home/thevifco/public_html/
