---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thevifco/repositories/the-vif-luxury-rivie
    - cd $DEPLOYPATH
    - /opt/cpanel/ea-nodejs20/bin/npm install
    - /opt/cpanel/ea-nodejs20/bin/npm run build
    - /bin/cp -R $DEPLOYPATH/dist/* /home/thevifco/public_html/
